language: rust
matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
   - os: osx
   - os: windows   
rust:
  - stable
cache: cargo # cache cargo-audit once installed
matrix:
  fast_finish: true
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo install --force cargo-audit  ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo generate-lockfile            ; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo audit ; fi
  - cargo test --verbose
