
[package]
name = "adblock"
version = "0.1.0"
authors = ["Andrius Aucinas <aaucinas@brave.com>"]
edition = "2018"

[dependencies]
addr = "0.2"
url = "1.7"
matches = "0.1"
lazy_static = "1.3"
regex = "1"
bitflags = "1.0"
itertools = "0.8"
idna = "0.1"
fasthash = "0.4"
serde =  { version = "1.0", features = ["derive", "rc"] }
bincode = "1.1"

[target.'cfg(any(unix, windows))'.dependencies]
rayon = "1.0"

[dev-dependencies]
criterion = "0.2"
csv = "1"
serde_json = "1.0"

[lib]
bench = false


[[bench]]
name = "bench_regex"
harness = false

[[bench]]
name = "bench_matching"
harness = false

[[bench]]
name = "bench_url"
harness = false

[[bench]]
name = "bench_rules"
harness = false

[features]

full-domain-matching = [] # feature has no explicit dependencies
