
[package]
name = "adblock"
version = "0.1.0"
authors = ["Andrius Aucinas <aaucinas@brave.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5"
addr = "0.2"
url = "1.7"
matches = "0.1"
lazy_static = "1.3"
regex = "1"
bitflags = "1.0"
punycode = "0.4"
itertools = "0.8"
rayon = "1.0"
fasthash = "0.4"
idna = "0.1"

[dev-dependencies]
criterion = "0.2"
env_logger = "0.5"
serde =  { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bench]]
name = "bench_matching"
harness = false

[[bench]]
name = "bench_url"
harness = false

[[bench]]
name = "bench_rules"
harness = false

[features]

full-domain-matching = [] # feature has no explicit dependencies
