name: CI

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            target: Linux
          - os: macos-latest
            target: Macos
          - os: windows-latest
            target: Windows

    env:
      # Take care when modifying this field; it's parsed naïvely by a script.
      RUSTFLAGS: --deny warnings

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # audit dependencies for severe vulnerabilities
      # (to deny warnings in the future, note that cargo audit requires additional arguments)
      - name: Cargo audit
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install --force cargo-audit
          cargo generate-lockfile
          cargo audit

      - name: Cargo build all
        run: .github/workflows/build-all.sh
        shell: bash

      - name: Cargo test
        env:
          BRAVE_SERVICE_KEY: ${{ secrets.BRAVE_SERVICE_KEY }}
        run: cargo test --verbose --features "content-blocking, resource-assembler"
